### ISSUE TITLE
[IMPROVEMENT] Add GithubActions workflows to PRs

### ISSUE THREAD

**Issue by faogustavo** [skrapeit/skrape.it#117]
I've just noticed that the current GitHub Actions workflows are just running on the master branch.
If you want, I can configure it to run on PRs.

**Comment by christian-draeger** [comment]
sure sounds great go for it :)

**Comment by faogustavo** [comment]
@christian-draeger just opened a PR with the improvement of the workflow ;) 
Just let me know if you need something more

**Comment by christian-draeger** [comment]
I want to add examples in the examples module. For the server side stuff it's no problem for me but since I am not an android dev #121 would be awesome.
It then can also be a playground to proove #93 is working or not and could run as part of the build chain maybe (don't know if that is possible with github actions)
