### ISSUE TITLE
[BUG] Skrape.It causes a stack dump when trying to run it from an Android application

### ISSUE THREAD

**Issue by Git-Jiro** [skrapeit/skrape.it#144]
**Describe the bug**
I get a stack trace when trying to use skrape.it from within an Android app.

Minimal example, gradle.build and a stack trace are in this gist:
https://gist.github.com/Git-Jiro/34e7f49d6abddfe825f53cc6df4d4a4d

**Expected behavior**
Scraper should not cause a stack trace.
(My code works fine in normal java / kotlin application)

**Comment by christian-draeger** [comment]
i will try to have a look asap. sorry for inconvenience

**Comment by Git-Jiro** [comment]
Hi!
No rush.
I found out version 1.0.0 works fine for me. So I use that version for now.

**Comment by christian-draeger** [comment]
Ok got it. It's because the http client has been refactored to use ktor Client with apache. We need to choose some http client implementation that will work properly on jvm as well as on Android like ktor client with okhttp or simular

**Comment by christian-draeger** [comment]
ok could test version 1.1.1 on android now and it works for me.
i added an example here --> https://github.com/skrapeit/skrape.it/blob/master/examples/android/README.md

**Comment by Git-Jiro** [comment]
Hi!
Thanks for providing a sample application.
However I have a small issue with the sample:
When I try to open it I get an error message like this here: https://issuetracker.google.com/issues/187470273?pli=1

The project file seems to have been created with the latest beta build of Android Studio Arctic Fox (2020.3.1) and does not work with Android Studio 4.2.1.

Improvement Idea to make the sample more useful for more people:
Recreate it with a "non beta build" of Android studio.

**Comment by christian-draeger** [comment]
Hey,
Thats true. I used the beta of android studio because I was i needed support for jetpack-compose (which I used in the example and which will be the defacto standard from this summer on).
But I agree that there obviously will be a lot of projects out there that are not able or don't want to migrate instantly. Thereby it would definitely still be a benefit to have a working Android example that builds on none beta releases of libraries as well as Android studio version.

Migration should be possible straight away, since the part of the example app where skrapeit is involved will not change really. I will try to add some example soon.
