### ISSUE TITLE
[QUESTION] Socket timeout on self signed SSL certs

### ISSUE THREAD

**Issue by nikoinist** [skrapeit/skrape.it#162]
Hello!
 I'm building a simple android app that is going to scrape data from a specific website, and I get socket timeouts on request calls for https sites with self signed certs. I tried a few different sites that have self signed ssl certs and always the same thing happens.  

 I tried using the **sslRelaxed** option for the request function  and playing around with different timeout values, but I can't make it work at all. 

Could someone point me in right direction what could be a problem, and or give me some sample code how to do it in case of self singed certs?

I haven't put a sample code since it is super trivial and similar to samples in the doc., since I just found the skrape.it lib and trying to evaluate it for an app.
Thank you!

**Comment by christian-draeger** [comment]
Hey could you provide some link to a page with a self signed cert so I can investigate?

**Comment by nikoinist** [comment]
Yes, I tried a few sites. This is the one I'm interested in scraping https://www.hep.hr/en 
I tried a few others with the ability to use http and https and always get the timeout on when using the ssl link.
Thanks!

**Comment by christian-draeger** [comment]
i quickly tried from local jvm project (no android involved) and it works fine for me
![image](https://user-images.githubusercontent.com/22223458/133652118-a1c28940-41ae-4f21-b458-6f814cbe436f.png)

maybe it is related to android somehow, i will try...

**Comment by nikoinist** [comment]
Thank you for taking time and testing it.

**Comment by nikoinist** [comment]
I'm really baffled by this. When I run unit test it works fine but when I use it in the app it timeouts on https calls.

**Comment by mufasa08** [comment]
I'm having the same issue. Have you figured it out? @nikoinist

**Comment by nikoinist** [comment]
> 
> 
> I'm having the same issue. Have you figured it out? @nikoinist

@mufasa08 No, sorry. Think I'll use a different lib.

**Comment by christian-draeger** [comment]
There seems to be a problem with the current fetcher implementation and Android.
A user in kotlin slack said he implemented an Fetcher based on ktor kohttp and everything worked fine.
Current fetcher implementation is based on ktor apache http client.

As a work around since I will find the time to fix this you could either implement an fetcher based on an http client that works on Android or if you first and foremost just need the html parsing feature the http stuff with any http client of your choice and than pass the corresponding  response body to the html parser

Sorry for inconvenience
