### ISSUE TITLE
MatchersKt cannot be represented in dex format.

### ISSUE THREAD

**Issue by mdaslamHossin** [skrapeit/skrape.it#60]
This occurs when trying to build in **android project**. Here is the details error message
Method name 'to be' in class '`it.skrape.matchers.MatchersKt`' cannot be represented in `dex `format.

**Comment by christian-draeger** [comment]
Hey rhx for reporting. Do have an example snippet?

**Comment by christian-draeger** [comment]
This is an androidTest issue. 
Android does not actually run Java class files, but uses a different kind of virtual machine (originally Dalvik) that uses the DEX format instead. As part of building your app it will take all your .class files and translates them into a single (or multiple for multidex) dex file. Without looking at the DEX spec it is clear that this format is more restrictive on symbol names and can as far as I know neither handle spaces nor backticks in function names. 

This is basically a DEX/android limitation. The only thing that works around this would be for Kotlin (or the dex compiler) to mangle the names to something legal (e.g. `toBe`) .

For cases like that skrape{it} provides the `toBe` matcher instead of `to be` to prevent the lack between android compiler and kotlin coding conventions at.
You'll find information about that in the [kotlin coding conventions docs](https://kotlinlang.org/docs/reference/coding-conventions.html) under **Names for test methods**. 

I will add a hint to the skrape{it} documentation.

:) nevertheless I would love to see your example of using skrape{it} for Android testing since I'm still looking for a good android example for the documentation.
