### ISSUE TITLE
[IMPROVEMENT] module split

### ISSUE THREAD

**Issue by skrapeit** [skrapeit/skrape.it#69]
Since skrape{it} is basically characterized by 3 functionalities that would also independently offer value for users, we also want to make them technically visible.

This will make it possible to separate/display functionalities individually at release as well as in the code.

for this reason a Gradle Multimodule project should be created:

the modules distinguish between:
* core
* html parser
* assertions
* http client
* browser client

Create and release separate Maven artifacts

**Comment by skrapeit** [comment]
it is already a multi-module project (with one module called core) that in clouds everything.
this module needs to be splitter into the ones described in the issue

**Comment by sleshJdev** [comment]
I need this feature as well. Seems that skrape is the only mature kotlin library to work with html. I need to do a simple thing like parse a small piece of html markup and scrap some data - no more, no less. Because the library is a monolith I should bring 13MB fat jar to get neede functionality even though the rest 80% of functionality is no neede at all.

**Comment by christian-draeger** [comment]
Yes I see your point. The html parse is the most important to get an own release. I assume and thereby totally agree with what u said. Most common use case is just parsing html.

>Seems that skrape is the only mature kotlin library to work with html

glad to here. If you like the library don't hesitate to give it a star to make it more popular and thereby also speed up its development if it will be visible to more potential contributors :)

**Comment by sleshJdev** [comment]
I'll try to prepare PR in the near future. No ETA, unfortunately.
